// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getCategory = `-- name: GetCategory :one
SELECT id, user_id, name, kind, parent_id, color, icon, archived_at, created_at FROM categories WHERE id = $1 AND user_id = $2
`

type GetCategoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Kind,
		&i.ParentID,
		&i.Color,
		&i.Icon,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, user_id, name, kind, parent_id, color, icon, archived_at, created_at FROM categories
WHERE user_id = $1 AND archived_at IS NULL
ORDER BY kind, name
`

func (q *Queries) ListCategories(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.Color,
			&i.Icon,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
