// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AccountType string

const (
	AccountTypeChecking   AccountType = "checking"
	AccountTypeSavings    AccountType = "savings"
	AccountTypeCreditCard AccountType = "credit_card"
	AccountTypeCash       AccountType = "cash"
	AccountTypeInvestment AccountType = "investment"
	AccountTypeLoan       AccountType = "loan"
	AccountTypeOther      AccountType = "other"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"accountType"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type CategoryKind string

const (
	CategoryKindIncome  CategoryKind = "income"
	CategoryKindExpense CategoryKind = "expense"
)

func (e *CategoryKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CategoryKind(s)
	case string:
		*e = CategoryKind(s)
	default:
		return fmt.Errorf("unsupported scan type for CategoryKind: %T", src)
	}
	return nil
}

type NullCategoryKind struct {
	CategoryKind CategoryKind `json:"categoryKind"`
	Valid        bool         `json:"valid"` // Valid is true if CategoryKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCategoryKind) Scan(value interface{}) error {
	if value == nil {
		ns.CategoryKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CategoryKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCategoryKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CategoryKind), nil
}

type TransactionKind string

const (
	TransactionKindIncome   TransactionKind = "income"
	TransactionKindExpense  TransactionKind = "expense"
	TransactionKindTransfer TransactionKind = "transfer"
)

func (e *TransactionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionKind(s)
	case string:
		*e = TransactionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionKind: %T", src)
	}
	return nil
}

type NullTransactionKind struct {
	TransactionKind TransactionKind `json:"transactionKind"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionKind) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionKind), nil
}

type Account struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"userId"`
	Name           string          `json:"name"`
	Type           AccountType     `json:"type"`
	Currency       string          `json:"currency"`
	InitialBalance decimal.Decimal `json:"initialBalance"`
	ArchivedAt     *time.Time      `json:"archivedAt"`
	CreatedAt      time.Time       `json:"createdAt"`
	UpdatedAt      time.Time       `json:"updatedAt"`
}

type Budget struct {
	ID          uuid.UUID       `json:"id"`
	UserID      uuid.UUID       `json:"userId"`
	CategoryID  uuid.UUID       `json:"categoryId"`
	Amount      decimal.Decimal `json:"amount"`
	Currency    string          `json:"currency"`
	PeriodStart time.Time       `json:"periodStart"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
}

type Category struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"userId"`
	Name       string       `json:"name"`
	Kind       CategoryKind `json:"kind"`
	ParentID   *uuid.UUID   `json:"parentId"`
	Color      *string      `json:"color"`
	Icon       *string      `json:"icon"`
	ArchivedAt *time.Time   `json:"archivedAt"`
	CreatedAt  time.Time    `json:"createdAt"`
}

type Transaction struct {
	ID                uuid.UUID       `json:"id"`
	UserID            uuid.UUID       `json:"userId"`
	AccountID         uuid.UUID       `json:"accountId"`
	CategoryID        *uuid.UUID      `json:"categoryId"`
	Kind              TransactionKind `json:"kind"`
	Amount            decimal.Decimal `json:"amount"`
	Currency          string          `json:"currency"`
	Description       *string         `json:"description"`
	OccurredAt        time.Time       `json:"occurredAt"`
	TransferAccountID *uuid.UUID      `json:"transferAccountId"`
	ExternalID        *string         `json:"externalId"`
	ExternalSource    *string         `json:"externalSource"`
	CreatedAt         time.Time       `json:"createdAt"`
	UpdatedAt         time.Time       `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"passwordHash"`
	DisplayName  *string   `json:"displayName"`
	BaseCurrency string    `json:"baseCurrency"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}
