// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error
	GetAccount(ctx context.Context, arg GetAccountParams) (Account, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error)
	ListCategories(ctx context.Context, userID uuid.UUID) ([]Category, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
