// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, account_id, category_id, kind, amount, currency,
    description, occurred_at, transfer_account_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, account_id, category_id, kind, amount, currency, description, occurred_at, transfer_account_id, external_id, external_source, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID            uuid.UUID       `json:"userId"`
	AccountID         uuid.UUID       `json:"accountId"`
	CategoryID        *uuid.UUID      `json:"categoryId"`
	Kind              TransactionKind `json:"kind"`
	Amount            decimal.Decimal `json:"amount"`
	Currency          string          `json:"currency"`
	Description       *string         `json:"description"`
	OccurredAt        time.Time       `json:"occurredAt"`
	TransferAccountID *uuid.UUID      `json:"transferAccountId"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Kind,
		arg.Amount,
		arg.Currency,
		arg.Description,
		arg.OccurredAt,
		arg.TransferAccountID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.OccurredAt,
		&i.TransferAccountID,
		&i.ExternalID,
		&i.ExternalSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1 AND user_id = $2
`

type DeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) DeleteTransaction(ctx context.Context, arg DeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, deleteTransaction, arg.ID, arg.UserID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, account_id, category_id, kind, amount, currency, description, occurred_at, transfer_account_id, external_id, external_source, created_at, updated_at FROM transactions WHERE id = $1 AND user_id = $2
`

type GetTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Kind,
		&i.Amount,
		&i.Currency,
		&i.Description,
		&i.OccurredAt,
		&i.TransferAccountID,
		&i.ExternalID,
		&i.ExternalSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, account_id, category_id, kind, amount, currency, description, occurred_at, transfer_account_id, external_id, external_source, created_at, updated_at FROM transactions
WHERE user_id = $1
ORDER BY occurred_at DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsParams struct {
	UserID uuid.UUID `json:"userId"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Kind,
			&i.Amount,
			&i.Currency,
			&i.Description,
			&i.OccurredAt,
			&i.TransferAccountID,
			&i.ExternalID,
			&i.ExternalSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
